### Get all meetings
GET localhost:8080/meeting
Authorization: Basic {{username}} {{password}}

### Get a meeting
GET localhost:8080/meeting/b4f44612-ceb6-4ced-927e-b7e92de10a74
Authorization: Basic {{username}} {{password}}

### Change attendance
POST localhost:8080/meeting/b4f44612-ceb6-4ced-927e-b7e92de10a74/attendance
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "member": "eea88c0b-28bd-4db7-8c36-aed90ec53ac8",
    "present": true
}

### End a meeting
POST localhost:8080/meeting/b4f44612-ceb6-4ced-927e-b7e92de10a74/end
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "endTime": "12:00:00.000"
}

### Create a meeting
PUT localhost:8080/meeting
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "date": "2019-01-01",
    "location": "Room 1",
    "orderedBy": "eea88c0b-28bd-4db7-8c36-aed90ec53ac8",
    "startTime": "10:00:00.000"
}
